repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: poetry run pytest
      language: system
      pass_filenames: false
    - id: coverage-badge
      name: coverage-badge
      entry: poetry run coverage-badge -o docs/coverage.svg -f
      language: system
      pass_filenames: false
